/gate/source/addSource gammapoint gps
/gate/source/gammapoint/gps/type 		Point
/gate/source/gammapoint/gps/centre 		0.0 0.0 2.0 cm
/gate/source/gammapoint/gps/particle 	gamma
/gate/source/gammapoint/gps/energy 		1000. keV
/gate/source/gammapoint/setActivity 	1000. Bq
#/gate/source/gammapoint/gps/confine 	MovingSource_phys
/gate/source/gammapoint/gps/angtype       	iso
#/gate/source/gammapoint/attachTo          	container
/gate/source/gammapoint/visualize  200 blue 3
