# SOURCECONTAINER
/gate/world/daughters/name                          container
/gate/world/daughters/insert                        cylinder
/gate/container/placement/setTranslation            0.0 0.0 20.0 mm
/gate/container/geometry/setRmin                    0 mm
/gate/container/geometry/setRmax                    1 mm
/gate/container/geometry/setHeight                  1 mm
/gate/container/geometry/setPhiStart                0 deg
/gate/container/geometry/setDeltaPhi                360 deg
/gate/container/setMaterial                         PMMA
/gate/container/vis/setVisible                      1
/gate/container/vis/forceWireframe
/gate/container/vis/setColor                        grey


